#!groovy

// DO NOT EDIT THIS FILE BY HAND -- FILE IS SYNCHRONIZED REGULARLY

node {
  currentBuild.result = "SUCCESS"

  // https://www.quernus.co.uk/2016/10/03/wipe-workspace-jenkins-2.0-deletedir/
  deleteDir() // wipe the workspace

  try {
    stage('Checkout') {
      checkout scm
    }

    stage('Build') {
      sh 'scripts/build.sh'
    }

    stage('Push') {
      sh 'scripts/push.sh'
    }
  }

  catch (err) {
    currentBuild.result = "FAILURE"
      throw err
  }
}
