#!/usr/bin/env bash
set -x

# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
#
# DO NOT EDIT THIS FILE BY HAND -- FILE IS SYNCHRONIZED REGULARLY

# Available environment variables
#
# BUILD_OPTS
# REPOSITORY
# VERSION

# Set default values

BUILD_OPTS=${BUILD_OPTS:-}
HASH_REPOSITORY=$(git rev-parse --short HEAD)

docker build \
    --build-arg "BRANCH=$BRANCH" \
    --build-arg "VERSION=$VERSION" \
    --label "io.osism.${REPOSITORY#osism/}=$HASH_REPOSITORY" \
    --tag "$REPOSITORY:$VERSION" \
    --squash \
    $BUID_OPTS .
