#!/usr/bin/env bash
set -x

# DO NOT EDIT THIS FILE BY HAND -- FILE IS SYNCHRONIZED REGULARLY

docker pull hadolint/hadolint
docker run --rm -v $(pwd)/.hadolint.yaml:/.hadolint.yaml -i hadolint/hadolint < Dockerfile
