#!/usr/bin/env bash
set -x

# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
#
# DO NOT EDIT THIS FILE BY HAND -- FILE IS SYNCHRONIZED REGULARLY

# Available environment variables
#
# DIRECTORY
# REPOSITORY
# VERSION

# Set default values

BUILD_OPTS=${BUILD_OPTS:-}

if [[ ! -z $DIRECTORY ]]; then
    pushd $DIRECTORY
fi

# https://github.com/jenkinsci/docker/blob/master/update-official-library.sh
version-from-dockerfile() {
    grep VERSION: Dockerfile | sed -e 's/.*:-\(.*\)}/\1/'
}

if [[ -z $VERSION ]]; then
    VERSION=$(version-from-dockerfile)
fi

docker push "$REPOSITORY:$VERSION"
docker rmi "$REPOSITORY:$VERSION"

if [[ ! -z $DIRECTORY ]]; then
    popd
fi
